apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:zezFp+PqB0jLclDWbWGVrHzPFe42PA2DIBT9S1KV9F+Jhs8s2sygg3WcPdYN5MqnjuRp0uHdzaomtbKr3vGXyLHn1CwcmWasnaQUzTZGpOMa,iv:WjS2rtVFUK0cHXFnx/cRUlL3smCfJDq0M88a3lwkK0k=,tag:toJnmWLkFZTH97Iu6c1zow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqpj0rky4ss9ha5pm86ymjpfavtqwtn3uzcp4ek5r8un4rzjt5csjdhrpu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWamRqUlViU0ZHN3haSE1M
            NkQ0T1pKa2ZZd210bEg0aEpzd2k3UUw3L1hNCldmODJZTmR1YXlLY0kySld2T1dF
            bW1tRDBFczE2bVZGZmFGTmNlRjB1T2MKLS0tIFFjK3d3ZWxnd3czQTg3b1R6R0k3
            b3RuN1lDTzZCaVNnNmh5QmtWTWRHekEKnkhnbC1bfpwKjlJhiqbiGAhti6O1iPtD
            Qc1aVDUeJa9uWxrcXss7wpAppKG+LJO1BwClKkRooBPqqG3v66IY+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T20:17:27Z"
    mac: ENC[AES256_GCM,data:wqsHryG+CYedg7i8GoEJDg9V8DxDH+rII1n7jmDa64tagAGSS7ji1Y6GTw8mFwZFPhVhYrlf38mIJE5SI04C0Suz4CfaL32khvVvIKwdH6FN51A+82QxxFv5aNoPDIYn1VEFfsZ2hzLUaUuE861E0w6q+nyGx7tr6T7QS5FzarU=,iv:uTyETAWyiK/YIc29LvytqY3dE4oSki5oHRvk3Z65Fyo=,tag:S/Y49wO9pAyybZ08VjHeTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
